name: Cypress E2E Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: npm install

    - uses: cypress-io/github-action@v2
      with:
        command: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --spec
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
